source 'https://rubygems.org'

gemspec

gem 'rack', ENV['RACK_VERSION'] || '~> 3'

group :development, :test do
  gem 'builder'
  gem 'markaby'
  gem 'rake'
  gem 'rubocop', '1.67.0'
  gem 'rubocop-capybara'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'simplecov'
  gem 'rack-test', require: 'rack/test'
  gem 'rspec'
  gem 'rspec-its'
  gem 'slim'
  gem 'sass'
  gem 'tapp'
  gem 'tilt', '>=2.0'
  gem 'RedCloth'
  gem 'bluecloth'
  gem 'coffee-script'
  gem 'contest'
  gem 'creole'
  gem 'erubis'
  gem 'haml'
  gem 'kramdown'
  # gem 'less'
  gem 'liquid'
  gem 'maruku'
  gem 'nokogiri'
  gem 'psych', '~> 3.0'
  gem 'rackup'
  gem 'radius'
  gem 'rdiscount'
  gem 'rdoc'
  # gem 'wikicloth'
  gem 'yajl-ruby'
  gem 'capybara'
  gem 'selenium-webdriver', '~> 4'
  # gem 'therubyracer'
  gem 'webrick'
end
