source 'https://rubygems.org'

gemspec

gem 'rack'

group :development, :test do
  gem 'rake'
  gem 'rubocop', '0.44.1'
  gem 'simplecov'
  gem 'rack-test', require: 'rack/test'
  gem 'rspec'
  gem 'rspec-its'
  gem 'slim'
  gem 'sass'
  gem 'tapp'
  gem 'tilt', '>=2.0'
  gem 'RedCloth'
  gem 'bluecloth'
  # gem 'builder'
  gem 'coffee-script'
  gem 'contest'
  gem 'creole'
  gem 'erubis'
  gem 'haml'
  gem 'kramdown'
  # gem 'less'
  gem 'liquid'
  # gem 'markaby'
  gem 'maruku'
  gem 'nokogiri'
  gem 'radius'
  gem 'rdiscount'
  gem 'rdoc'
  # gem 'wikicloth'
  gem 'yajl-ruby'
  gem 'capybara'
  gem 'selenium-webdriver', '~>2.5'
  # gem 'therubyracer'
end
